#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Application;
use Framework\Server\Swoole\SwooleHttpServer;
use Framework\Templating\Renderer\TemplateRenderer;
use Framework\Templating\Blade\BladeIntegration;
use Framework\Templating\Twig\TwigIntegration;
use Framework\Web\WebFrontend;

require_once __DIR__ . '/vendor/autoload.php';

(new WebFrontend(
    new Application(__DIR__),
    new SwooleHttpServer(
        port: 443,
        config: [
            'ssl_cert_file' => __DIR__ . '/certificates/cert.pem',
            'ssl_key_file' => __DIR__ . '/certificates/cert-key.pem',
        ],
        sockType: SWOOLE_SOCK_TCP | SWOOLE_SSL
    )
))
    ->addRenderer(
        (new TemplateRenderer())
            ->addIntegration(new TwigIntegration(__DIR__ . '/templates'))
            ->addIntegration(new BladeIntegration(__DIR__ . '/templates'))
    )
    ->run()
;
